trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: echo "Building application"
  displayName: Build Step

- script: echo "Running Tests"
  displayName: Test Step

- script: echo "Deploying Application"
  displayName: Deploy Step